env:
  # Telegram
  TG_CHAT: "@Sikedumps"
  TG_TOKEN: ENCRYPTED[!3bf69b5334ddc8bdccaebfc6bf2c17a30a85daa762d5157430a82a1c11a0f37b3190bdaea1f692ec21859d858f3f153d!]
  
  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: rex_vili
  GITLAB_TOKEN: ENCRYPTED[!32695bba9c1adc7a20b494b305e770cc5e2db99274636a9a815def379a3f31aab916cd8227118ff9a3c9f78b2be9786e!]

  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[991b9f9111329b8e8135040d22ec23508a560304dac1ef13d515eef2cdef4c15bbfaf329403d55b913af2b74c9e08edb]

task:
  name: "DumprX-1"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "SuperiorPsycho"
      - git config --global user.email "pranjal.loner@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(cat ../*.json | jq -r .\"1\")

task:
  name: "DumprX-2"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "SuperiorPyscho"
      - git config --global user.email "pranjal.loner@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(cat ../*.json | jq -r .\"2\")

task:
  name: "DumprX-3"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "SuperiorPsycho"
      - git config --global user.email "pranjal.loner@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(cat ../*.json | jq -r .\"3\")

task:
  name: "DumprX-4"
  only_if: $CIRRUS_REPO_OWNER == 'DumprX'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "SuperiorPsycho"
      - git config --global user.email "pranjal.loner@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(cat ../*.json | jq -r .\"4\")
